<table width="100%" class="table" border="0" cellspacing="0" cellpadding="0">

 <tr class="head"> <td width="200"><strong>Course Name</strong></td> 
 <td width="200"><strong>Description</strong></td> 
 <td width="150"><strong>Target Audience</strong></td> 
 <td><strong>Course Offering</strong></td> 
 </tr>
 <tr> <td valign="top" class="title">Introduction to Seasonality <br /><span id="warningText">REGISTRATION CLOSED</span><!---<a class="button" href="index.php?id=training_catalogue_form&cid=<?php echo urlencode("Introduction to Seasonality"); ?>">Register</a>---></td> <td valign="top">Why can't I find good blueberries in April?  Why do people sniff cantaloupe at the supermarket?  Are bananas really in season all year long? Knowing which fruits and vegetables are in season gives you a clue as to what produce is likely to be on sale at given times in the year. At the very least, it can help you plan your shopping list - and skip the expensive, out of season items. It can give you ideas for menu planning, as well: there's a reason that holiday favorites are popular at certain times of the year. Please join our produce experts for an introduction to what's great right now.</td> <td valign="top">All FreshDirect Employees.</td> <td valign="top">Thursday, July 16, 11-12 PM</td> 
 </tr>
 <tr> <td valign="top" class="title">Introduction to Powerpoint <br /><span id="warningText">COMING SOON</span><!---<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Introduction to Powerpoint"); ?>">Register</a>---></td> <td valign="top">Leave your old templates and design ideas behind, and we'll show you how to use PowerPoint to its full capability to design memorable, visually exciting presentations that get the results you want - for any audience. You'll learn how to use PowerPoint's newest multimedia tools and design features to create remarkable presentations that are guaranteed to amaze your audience.</td> <td valign="top">This course is designed for students who are interested in learning the fundamentals needed to create and modify basic PowerPoint presentations.</td> <td valign="top">Quarterly</td> 
 </tr>
 <tr> <td valign="top" class="title">Microsoft Excel - Level I <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Microsoft Excel - Level I"); ?>">Register</a>--></td> <td valign="top">This Microsoft Excel training course is aimed at individuals who have a basic competency with using a computer - for example you will ideally have the skill to use a mouse, have used the internet before and are comfortable with using Windows as your operating system.</td> <td valign="top">Although knowledge of how to navigate in a Windows environment is helpful, this class was designed for the Excel novice. Students will learn basic worksheet skills and how to work with data in worksheets.</td> <td valign="top">Quarterly</td> 
 </tr>
 <tr> <td valign="top" class="title">Microsoft Excel - Level II <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Microsoft Excel - Level II"); ?>">Register</a>--></td> <td valign="top">In Level 1, you created, edited, formatted and printed basic spreadsheets. You now have a need to streamline repetitive tasks and display spreadsheet data in more visually effective ways. In this course, you will use MS Office Excel to streamline and enchance your spreadsheets with advances formulas, charts, graphs and pivot tables.</td> <td valign="top">In this course you will create templates, sort and filter data, import and export data, and analyze data.</td> <td valign="top">Quarterly</td> 
 </tr>
 <tr> <td valign="top" class="title">Microsoft Outlook <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Microsoft Outlook"); ?>">Register</a>--></td> <td valign="top">Learn not only the basic knowledge of the software, including how to create and format email, but also how to schedule events, plan meetings, book conference rooms and more.</td> <td valign="top">This course is designed for people with a basic understanding of Microsoft Outlook who want to learn to manage their calendars more efficiently. </td> <td valign="top">Quarterly</td> 
 </tr>
 <tr> <td valign="top" class="title">Business Objects <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Business Objects"); ?>">Register</a>--></td> <td valign="top">Business Objects is a reporting tool for SQL compliant databases. It allows users to prepare custom reports from a number of databases through a Business Objects Universe, which in turn facilitates advanced reporting and data analysis. This course is designed for those who have little or no previous experience and who wish to learn how to build queries and create reports using Business Objects. The course aims to provide a good basic grounding in the use of Business Objects for presenting and analysing information, and for sharing that information with others within your organization.</td>  <td valign="top"></td> <td valign="top">Quarterly</td> 
 </tr>
 <tr> <td valign="top" class="title">English as a Second Language (ESL) <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("English as a Second Language (ESL)"); ?>">Register</a>--></td> <td valign="top">Improve your listening, speaking, reading and grammar skills, and gain confidence in your ability to use English in a variety of situations. Classes range from beginning to advanced levels.</td> <td valign="top">Classes available for students at all levels who are looking to learn or improve their English speaking and comprehension skills.</td> <td valign="top">Weekly</td> 
 </tr>
 
 <tr> <td valign="top" class="title">Leadership Development (Leads) <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Leadership Development (Leads)"); ?>">Register</a>--></td> <td valign="top">So you've promoted to a lead position; now what? This course will help you learn the fundamental leadership skills needed for your new position.</td> <td valign="top">This class is targeted to all leads in plant and transportation.</td> <td valign="top">3 sessions, Semi-annual</td> 
 </tr>
 
 <tr> <td valign="top" class="title">Leadership Development (Managers) <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Leadership Development (Managers)"); ?>">Register</a>--></td> <td valign="top">Learn the difference between leadership and management and how to be more effective as your role changes within the organization.  </td> <td valign="top">The material for this course will benefit new people managers, as well as new supervisors in all departments.</td> <td valign="top">4 sessions, Semi-annual</td> 
 </tr>

 <tr> <td valign="top" class="title">Harassment Prevention Training <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Harassment Prevention Training"); ?>">Register</a>--></td> <td valign="top">Harassment is serious business. It can create tension in the workplace, reduce productivity, and potentially lead to financial devistation. This course is designed to help all employees understand what harassment is and what to do about it.</td> <td valign="top">This class is designed for exempt level employees who supervise employees.</td> <td valign="top">Once per year, 3 sessions</td> 
 </tr>
 <tr> <td valign="top" class="title">Interview Skills Training <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Interview Skills Training"); ?>">Register</a>--></td> <td valign="top">Making poor hiring decisions (and keeping bad hires) based on deficient interviewing skills costs companies millions of dollars every year. This class helps leaders develop the proven skill sets to interview and find the best candidate every time.</td> <td valign="top">Anyone who has hiring responsibility will want to take this class.</td> <td valign="top">Quarterly</td> 
 </tr>

 <tr> <td valign="top" class="title">Unemployment Training <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Unemployment Training"); ?>">Register</a>--></td> <td valign="top">The topics will be the types of documentation/detail needed to prevail at unemployment proceedings, what type of cases can be decided at the early determination phase (where no testimony at hearing are necessary), what happens at an unemployment hearing etc. </td> <td valign="top">This class is designed for managers who have responsibility around disciplines and terminations.  </td> <td valign="top">Quarterly</td> 
 </tr>
 
 <tr> <td valign="top" class="title">Introduction to the Intranet <br /><span id="warningText">COMING SOON</span><!--<a class="button" href="index.php?id=training_catalogue_form&cid=<?php //echo urlencode("Introduction to the Intranet"); ?>">Register</a>--></td> <td valign="top">This introductory class will teach you the basics of what an Intranet is, why is it useful for a company, and the software that is used to power the FreshDirect Intranet. It will also give you a basic understanding on how you can use this software to publish, maintain, and share documents with the rest of the company. </td> <td valign="top">All FreshDirect Employees</td> <td valign="top">Quarterly</td> 
 </tr>
</table>